"""student table

Revision ID: 921690e1a49d
Revises: 
Create Date: 2020-03-25 19:42:59.942268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921690e1a49d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clss', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', name='sexenum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('siblings', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
